"""add_wallet_unique_constraint_and_idempotency_records

Revision ID: 1a8c39240071
Revises: 
Create Date: 2026-03-13 09:40:47.206819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8c39240071'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# sql delete duplicate rows in wallet table
# -- keep row with most renctly created 
# DELETE FROM wallets
# WHERE id NOT IN (
#     SELECT DISTINCT ON (owner_id, currency) id
#     FROM wallets
#     ORDER BY owner_id, currency, created_at DESC
# )

# -- keep row with samlleset id
# DELETE FROM wallets
# WHERE id NOT IN (
#     SELECT MIN(id)
#     FROM wallets
#     GROUP BY owner_id, currency
# );
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'user_id', name='uq_idempotency_key_user')
    )
    op.create_index(op.f('ix_idempotency_records_idempotency_key'), 'idempotency_records', ['idempotency_key'], unique=False)
    # Remove duplicate wallets before adding unique constraint — keep the newest per (owner, currency)
    op.execute("""
        DELETE FROM wallets
        WHERE id NOT IN (
            SELECT DISTINCT ON (owner_id, currency) id
            FROM wallets
            ORDER BY owner_id, currency, created_at DESC
        )
    """)
    op.create_unique_constraint('uq_wallet_owner_currency', 'wallets', ['owner_id', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_owner_currency', 'wallets', type_='unique')
    op.drop_index(op.f('ix_idempotency_records_idempotency_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
