"""transfer_state_machine

Revision ID: 879eff3ad6c5
Revises: 1a8c39240071
Create Date: 2026-03-14 22:45:52.556888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '879eff3ad6c5'
down_revision: Union[str, None] = '1a8c39240071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idempotency_records_idempotency_key', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('quotes')
    op.add_column('transactions', sa.Column('rate', sa.Numeric(precision=28, scale=8), nullable=True))
    op.add_column('transactions', sa.Column('receive_amount', sa.Numeric(precision=28, scale=8), nullable=True))
    # Add expires_at as nullable first, backfill, then enforce NOT NULL
    op.add_column('transactions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE transactions SET expires_at = created_at + INTERVAL '60 seconds' WHERE expires_at IS NULL")
    op.alter_column('transactions', 'expires_at', nullable=False)
    op.add_column('transactions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # Backfill completed_at for existing completed transactions
    op.execute("UPDATE transactions SET completed_at = created_at WHERE status = 'completed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'completed_at')
    op.drop_column('transactions', 'expires_at')
    op.drop_column('transactions', 'receive_amount')
    op.drop_column('transactions', 'rate')
    op.create_table('quotes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_wallet_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('to_wallet_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('send_amount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('receive_amount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('from_currency', postgresql.ENUM('USD', 'EUR', 'GBP', 'BTC', name='currency_enum'), autoincrement=False, nullable=False),
    sa.Column('to_currency', postgresql.ENUM('USD', 'EUR', 'GBP', 'BTC', name='currency_enum'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], name='quotes_from_wallet_id_fkey'),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], name='quotes_to_wallet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='quotes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quotes_pkey')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='idempotency_records_pkey'),
    sa.UniqueConstraint('idempotency_key', 'user_id', name='uq_idempotency_key_user')
    )
    op.create_index('ix_idempotency_records_idempotency_key', 'idempotency_records', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###
